name: tests

on: [push, pull_request, workflow_dispatch]
jobs:

  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.9",
          "3.10",
          #"3.11"
          ]
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/action.yml
        with:
          python-version: ${{ matrix.python-version }}
      - name: test
        run: |
          python -m pytest

  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          #"3.9",
          "3.10",
          #"3.11"
          ]
        os: [macos14]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/action-macos-arm64.yml
        with:
          python-version: ${{ matrix.python-version }}
      - name: test
        run: |
          python -m pytest
